export const LIST_LIST_REQUEST = 'LIST_LIST_REQUEST'
export const LIST_LIST_SUCCESS = 'LIST_LIST_SUCCESS'
export const LIST_LIST_FAIL = 'LIST_LIST_FAIL'

export const LIST_DETAILS_REQUEST = 'LIST_DETAILS_REQUEST'
export const LIST_DETAILS_SUCCESS = 'LIST_DETAILS_SUCCESS'
export const LIST_DETAILS_FAIL = 'LIST_DETAILS_FAIL'
export const LIST_DETAILS_RESET = 'LIST_DETAILS_RESET'

export const LIST_CREATE_REQUEST = 'LIST_CREATE_REQUEST'
export const LIST_CREATE_SUCCESS = 'LIST_CREATE_SUCCESS'
export const LIST_CREATE_FAIL = 'LIST_CREATE_FAIL'
export const LIST_CREATE_RESET = 'LIST_CREATE_RESET'

export const LIST_DELETE_REQUEST = 'LIST_DELETE_REQUEST'
export const LIST_DELETE_SUCCESS = 'LIST_DELETE_SUCCESS'
export const LIST_DELETE_FAIL = 'LIST_DELETE_FAIL'
export const LIST_DELETE_RESET = 'LIST_DELETE_RESET'

export const LIST_UPDATE_REQUEST = 'LIST_UPDATE_REQUEST'
export const LIST_UPDATE_SUCCESS = 'LIST_UPDATE_SUCCESS'
export const LIST_UPDATE_FAIL = 'LIST_UPDATE_FAIL'
export const LIST_UPDATE_RESET = 'LIST_UPDATE_RESET'