# Generated by Django 4.0.5 on 2022-06-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_list_completed_list_deadline_list_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadline',
            new_name='completedAt',
        ),
        migrations.AddField(
            model_name='task',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
